# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      versionName:
        description: 'Version (ie 0.0.1)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create_relase_branch:
    # The type of runner that the job will run on
    uses: EmersonOliver/devops-java-workflow/.github/workflows/create_release_branch.yml@1.0.0
    with:
      versionName: ${{github.event.inputs.versionName}}
    secrets: inherit
